site_name: Columbia Gadget Works Info Pages
repo_url: https://github.com/ColumbiaGadgetWorks/InfoSheets
edit_uri: edit/master/docs/
site_url: https://cgwinfosheets.netlify.app

plugins:
  - search
  - macros

theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: orange
  logo: assets/cgw-logo.png
  favicon: assets/cgw-logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Equipment:
    - Laser Cutter: laser.md
    - Vinyl Cutter: vinyl-cutter.md
    - 3D Printer: 3d-printer.md
    - Shapeoko CNC: shapeoko-cnc.md
  - Equipment Log: equipment-log.md

extra_css:
  - stylesheets/extra.css
